default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db

development:
  <<: *default
  database: hackz_development

test:
  <<: *default
  database: hackz_test

production:
  <<: *default
  database: Bizibl
  host: <%= ENV['HACKZ_DB_HOST'] %>
  username: <%= ENV['HACKZ_DB_USERNAME'] %>
  password: <%= ENV['HACKZ_DB_PASSWORD'] %>